Repository QAB-LABS/QAB-HUB, pull requests merged in 2019-10, with the labels that each got.

#4 Feature Backend setup because I forgot to switch branches.
  README-boilerplate.md
  client/package-lock.json
  client/package.json
  client/src/actions/index.js
  client/src/apis/backend.js
  client/src/components/GameDetails.jsx
  client/src/components/GameDetailsRow.jsx
  client/src/components/pages/AddCountry.jsx
  client/src/components/pages/Countries.jsx
  client/src/components/pages/Home.jsx
  client/src/logo.svg
  client/src/registerServiceWorker.js
  package.json
  server/app.js
  server/configs/cloudinary.js
  server/configs/database.js
  server/models/Category.js
  server/models/Chat.js
  server/models/ChatMessage.js
  server/models/Comment.js
  server/models/Country.js
  server/models/Game.js
  server/models/Like.js
  server/models/Post.js
  server/models/Review.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/passport/index.js
  server/passport/localStrategy.js
  server/passport/serializers.js
  server/routes/auth.js
  server/routes/comments.js
  server/routes/countries.js
  server/routes/games.js
  server/routes/index.js
  server/routes/posts.js
  server/routes/reviews.js
Labels: enhancement

#9 Feature seed db
  .gitignore
  .vscode/settings.json
  package.json
  server/bin/categories.json
  server/bin/seeds.js
  server/configs/database.js
  server/models/Merchant.js
  server/models/User.js
  server/package-lock.json
  server/package.json
Labels: enhancement

#13 Feature frontend api interface
  .vscode/settings.json
  client/src/apis/backend.js
  client/src/apis/backend/comments.js
  client/src/apis/backend/error.js
  client/src/apis/backend/games.js
  client/src/apis/backend/likes.js
  client/src/apis/backend/merchants.js
  client/src/apis/backend/posts.js
  client/src/apis/backend/prices.js
  client/src/apis/backend/reviews.js
  client/src/apis/backend/user.js
  client/src/components/App.jsx
  client/src/components/MainNavbar/MainNavbar.jsx
Labels: enhancement

#14 Feature frontend api interface
  client/src/apis/backend/comments.js
  client/src/apis/backend/games.js
  client/src/apis/backend/likes.js
  client/src/apis/backend/merchants.js
  client/src/apis/backend/posts.js
  client/src/apis/backend/prices.js
  client/src/apis/backend/reviews.js
Labels: bug

#15 Feature redux actions
  .codeclimate.yml
  client/src/actions/games.js
  client/src/actions/index.js
  client/src/actions/merchants.js
  client/src/actions/posts.js
  client/src/actions/types.js
  client/src/actions/users.js
  client/src/components/App.jsx
  client/src/components/GamesList/GamesList.jsx
  client/src/components/GoogleAuth/GoogleAuth.jsx
  client/src/reducers/commentsReducer.js
  client/src/reducers/gamesReducer.js
  client/src/reducers/index.js
  client/src/reducers/likesReducer.js
  client/src/reducers/merchantsReducer.js
  client/src/reducers/pricesReducer.js
  client/src/reducers/reviewsReducer.js
  server/bin/comments.json
  server/bin/games.json
  server/bin/merchants.json
  server/bin/reviews.json
  server/models/Game.js
  server/models/Price.js
  server/models/Review.js
  server/models/User.js
  server/routes/comments.js
  server/routes/games.js
  server/routes/reviews.js
  server/routes/user.js
Labels: enhancement

#23 Just some needed backend changes
  server/models/Category.js
  server/models/Game.js
  server/models/Like.js
  server/models/Mechanic.js
  server/models/Rating.js
  server/models/Review.js
  server/routes/games.js
  server/routes/mechanics.js
  server/routes/ratings.js
Labels: bug, enhancement

#26 Feature game listing
  client/package-lock.json
  client/package.json
  client/src/actions/filters.js
  client/src/actions/games.js
  client/src/actions/types.js
  client/src/apis/backend/games.js
  client/src/components/Games/GameDetails.jsx
  client/src/components/Games/GameDetailsRow.jsx
  client/src/components/Games/GamesList.jsx
  client/src/components/Games/GamesList.scss
  client/src/components/UserCard/UserCard.jsx
  client/src/components/generic/Filter.jsx
  client/src/components/pages/Games.jsx
  client/src/components/pages/Profile.jsx
  client/src/reducers/filtersReducer.js
  client/src/reducers/gamesReducer.js
  client/src/reducers/index.js
  package-lock.json
  package.json
  server/bin/seeds.js
  server/models/Game.js
  server/package-lock.json
  server/package.json
  server/passport/localStrategy.js
  server/routes/auth.js
  server/routes/categories.js
  server/routes/comments.js
  server/routes/games.js
  server/routes/likes.js
  server/routes/merchants.js
  server/routes/posts.js
  server/routes/prices.js
  server/routes/reviews.js
  server/routes/users.js
Labels: enhancement

#60 Populates author information on home page
  client/src/actions/posts.js
  client/src/actions/reviews.js
  client/src/apis/backend/reviews.js
  client/src/components/pages/Home.jsx
Labels: bugfix
